version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  todo:
    build: .
    environment:
      - PORT=3000
  
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db


volumes:
  mongo-db: