version: '3'
services:
  todo:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=alireza
      - MONGO_PASSWORD=mypassword
    ports:
      - "3000:3000"
    command: npm run dev
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alireza
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

    